{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Time to respond to request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "request_creation_latency{source=\"jwt-pizza-service\"}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_http_requests_total{method=\"all\"}[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(request_http_requests_total{method=\"PUT\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(request_http_requests_total{method=\"POST\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_http_requests_total{method=\"GET\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_http_requests_total{method=\"DELETE\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Pizza sales / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_pizzas_sold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Count"
    },
    {
     "expr": "rate(request_revenue_generated{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Failed Order Creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "request_creation_failures{source=\"jwt-pizza-service\"}",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "request_system_memory_usage", "legendFormat": "Memory" },
    {
     "expr": "request_system_cpu_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Authentications / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(request_auth_attempts_successful{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(request_auth_attempts_failed{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "request_system_cpu_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "request_active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  }
 ]
}